### ISSUE TITLE
out of memory when training in OASIS dataset

### ISSUE THREAD

**Issue by Runshi-Zhang** [tzayuan/TransMatch_TMI#8]
When TransMatch was run in OASIS dataset(using your LPBA40_config and the input size (160, 192, 224)), the GPU memory was over 24GB in NVIDIA GeForceRTX 3090Ti GPUs (24 GB of VRAM).

**Comment by ZhaiJiaKai** [comment]
> 在 OASIS 数据集中运行 TransMatch 时（使用您的LPBA40_config和输入大小 （160， 192， 224）），NVIDIA GeForceRTX 3090Ti GPU 中的 GPU 内存超过 24GB（24 GB 的 VRAM）。

I also encounter the same problem, have you solved it?

**Comment by tzayuan** [comment]
Hi, @Runshi-Zhang @ZhaiJiaKai 
I apologize for the delay in replying due to being busy with other projects. Please check if the machine corresponding to the 24G graphics card (e.g. nvidia RTX 3090) is running any other programs that consume video memory, and you can end these processes as much as possible without crashing the machine, in order to satisfy the demand for training at OASIS (24177MB of video memory is required according to our experimental setup). If you still have problems, please feel free to contact me.
